title: Open Data For Arlington, MA
tagline: Transparency in town government through open data.
description: Vetted and source-annotated open data for Arlington, MA town government.
email: &email ArlingtonMAInfo@gmail.com
social:
  links:
    - https://twitter.com/ArlingtonMAInfo

author:
  avatar    : &logo /assets/images/logo.jpg
  location  : Arlington, MA
  email     : *email
  twitter   : ArlingtonMAInfo
    
# Build, theme, style settings
data_source: data # Override standard location
url: https://arlingtonma.info # jekyll-sitemap
repository: ArlingtonMA/arligntonma.info
branch: master
remote_theme: "mmistakes/minimal-mistakes@4.19.2"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
minimal_mistakes_skin: default
search: true
markdown: kramdown
permalink: /:categories/:title/
timezone: America/New_York # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

analytics:
  provider: custom # false (default), google, google-universal, custom
  google:
    tracking_id: G-9SCH3S83JG
    anonymize_ip: true

google:
  search_engine_id: 

footer:
  links:
    - label: About
      icon: fa fa-fw fa-address-card
      url: /about
    - label: Credits
      icon: fa fa-fw fa-hand-holding-heart
      url: /colophon
    - label: Terms & Privacy
      icon: fa fa-fw fa-gavel
      url: /terms
    - label: Twitter
      icon: fab fa-twitter
      url: https://twitter.com/ArlingtonMAInfo

# jekyll-seo-tag
logo: *logo

# Defaults
defaults:
  - scope: # default - pages
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: false
      share: true
      related: false
      sidebar:
        nav: main
  - scope: # default - posts
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
      sidebar:
        nav: main
  - scope: # _pages path
      path: _pages
      type: pages
    values:
      layout: single
      author_profile: false
      share: true
      related: true
      sidebar:
        nav: main
  - scope: # _newsorgs collection
      path: ""
      type: newsorgs
    values:
      layout: newsorg
      author_profile: false
      share: true
      related: true
      sidebar:
        nav: main

collections:
  newsorgs:
    output: true
    sort_by: name
    permalink: /:collection/:path

include:
  - _pages

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/